### ISSUE TITLE
Remove nix?

### ISSUE THREAD

**Issue by dfordivam** [ExtremaIS/ttc-haskell#3]
since ttc is a library I think it does not need default.nix and shell.nix

The reason I recommend removing these is because you have specified hard coded nixpkgs, which the user of ttc might not want to use. And since there is default.nix, it could (would?) interfere with the other nix expressions importing it (via callCabal2nix, or other mechanisms)

**Comment by TravisCardwell** [comment]
Hi Divam!

Thank you very much for the feedback!

> since ttc is a library I think it does not need default.nix and shell.nix
>
> The reason I recommend removing these is because you have specified hard coded nixpkgs, which the user of ttc might not want to use. And since there is default.nix, it could (would?) interfere with the other nix expressions importing it (via callCabal2nix, or other mechanisms)

I had no idea that the existence of a `default.nix` file in the repository affects Nix users who use the library in their own software.  I had been under the impression that it was (only) loaded by `nix` commands when executed in the same directory.  I did not think that it could interfere in the production of other software because I thought that the package would be pulled from Hackage, and my `ttc.cabal` file explicitly does *not* include the Nix configuration files as `extra-source-files` so that they are not included in `sdist` tarballs on Hackage.

Thank you for pointing out my mistake!  The `default.nix` file definitely needs to be removed.

I need to figure out a new way to configure Nix environments for development and testing of the library.  I would like to be able to run shells for each of the supported GHC versions, and I would really like to implement a version of the `make test-all` command using Nix.  I imagine that this will entail a common implementation (perhaps named `dev.nix`) and a separate file for each supported GHC version (`dev-9.0.1.nix` for example) that specifies the `nixpkgs` revision and GHC version.

I have searched for other projects that do this but have not found one yet.  It seems that most projects build against a fixed GHC version (as well as fixed dependency versions).  When I asked a Nix-knowledgeable friend about how people test against a range of compiler and dependency versions, he suggested that they do not do so within Nix and instead rely on CI (not using Nix).  That does not work for me.  I sometimes need to test against old as well as new compilers as I develop, when it is not acceptable to commit each iteration, and I prefer to catch bugs *before* they make it to CI in general.

If you happen to know of a project that would serve as a good example for me, please let me know.  Any advice is welcome as well.  Thanks again!

**Comment by TravisCardwell** [comment]
Based on Divam's pull request, I did a fair bit of refactoring and now have a simplified Nix configuration.

* There is no `default.nix` to cause problems when using the library via Nix.
* The `shell.nix` file can select an appropriate `nixpkgs` revision based on the `compiler` argument.  See the documentation in the file comments for details.
* The `test-all.nix` file can be used to test against all supported GHC versions.  See the documentation in the file comments for details.

Thank you, Divam!
